#!/bin/sh

for ARG in $@; do
    if [ -f "$ARG" ]; then

        XIB_FILENAME=$(basename "$ARG" ".xib")  # get file name without extension
        ibtool --compile "Resources/""$XIB_FILENAME"".nib" "$ARG";

    fi
done
